const DOM = {};
const AppState = { type: 'couplet', theme: '', style: 'classic', occasion: 'newyear', currentContent: '', works: [] };
function initDOM() { DOM.themeInput = document.getElementById('theme-input'); DOM.style = document.getElementById('style'); DOM.occasion = document.getElementById('occasion'); DOM.occasionWrap = document.getElementById('occasion-wrap'); DOM.btnGenerate = document.getElementById('btn-generate'); DOM.resultArea = document.getElementById('result-area'); DOM.content = document.getElementById('content'); DOM.collectionPanel = document.getElementById('collection-panel'); DOM.collectionList = document.getElementById('collection-list'); DOM.collectionOverlay = document.getElementById('collection-overlay'); DOM.settingsModal = document.getElementById('settings-modal'); DOM.toast = document.getElementById('toast'); }
function initEvents() {
    document.querySelectorAll('.type-btn').forEach(btn => btn.addEventListener('click', () => { document.querySelectorAll('.type-btn').forEach(b => b.classList.remove('active')); btn.classList.add('active'); AppState.type = btn.dataset.type; DOM.occasionWrap.classList.toggle('hidden', btn.dataset.type !== 'couplet'); }));
    DOM.themeInput.addEventListener('input', () => AppState.theme = DOM.themeInput.value);
    DOM.style.addEventListener('change', () => AppState.style = DOM.style.value);
    DOM.occasion.addEventListener('change', () => AppState.occasion = DOM.occasion.value);
    DOM.btnGenerate.addEventListener('click', generate);
    document.getElementById('btn-save').addEventListener('click', saveWork);
    document.getElementById('btn-collection').addEventListener('click', () => { DOM.collectionPanel.classList.add('open'); DOM.collectionOverlay.classList.remove('hidden'); });
    document.getElementById('btn-close-collection').addEventListener('click', closeCollection); DOM.collectionOverlay.addEventListener('click', closeCollection);
    document.getElementById('btn-settings').addEventListener('click', () => { DOM.settingsModal.classList.add('show'); loadSettings(); });
    document.getElementById('btn-close-settings').addEventListener('click', () => DOM.settingsModal.classList.remove('show'));
    document.getElementById('btn-cancel-settings').addEventListener('click', () => DOM.settingsModal.classList.remove('show'));
    document.getElementById('btn-save-settings').addEventListener('click', saveSettings);
    document.querySelectorAll('.example-btn').forEach(btn => btn.addEventListener('click', () => loadExample(btn.dataset.example)));
}
const EXAMPLES = { spring: { type: 'couplet', theme: '新年祝福、万事如意', style: 'festive' }, love: { type: 'seven', theme: '月下相思', style: 'romantic' }, career: { type: 'couplet', theme: '事业成功、步步高升', style: 'inspiring' }, acro: { type: 'acrostic', theme: '前程似锦', style: 'classic' } };
function loadExample(key) { const ex = EXAMPLES[key]; if (!ex) return; document.querySelectorAll('.type-btn').forEach(b => b.classList.remove('active')); document.querySelector(`.type-btn[data-type="${ex.type}"]`)?.classList.add('active'); AppState.type = ex.type; DOM.themeInput.value = ex.theme; AppState.theme = ex.theme; DOM.style.value = ex.style; AppState.style = ex.style; DOM.occasionWrap.classList.toggle('hidden', ex.type !== 'couplet'); showToast('info', '已填入', '点击生成作品'); }
async function generate() { DOM.resultArea.classList.remove('hidden'); DOM.content.innerHTML = ''; AppState.currentContent = ''; await AIService.generate(AppState.type, AppState.theme, AppState.style, AppState.occasion, (t) => { AppState.currentContent += t; DOM.content.innerHTML = formatContent(AppState.currentContent); }, () => showToast('success', '创作完成', ''), (e) => showToast('error', '生成失败', e.message)); }
function formatContent(text) { return text.replace(/上联：(.+)/g, '<div class="text-red-800 mb-2">🔴 上联：<span class="font-bold">$1</span></div>').replace(/下联：(.+)/g, '<div class="text-red-800 mb-2">🔴 下联：<span class="font-bold">$1</span></div>').replace(/横批：(.+)/g, '<div class="text-amber-700 text-3xl font-bold my-4 border-b-2 border-amber-300 pb-2">🏮 横批：$1</div>').replace(/【(.+?)】/g, '<span class="text-gray-600 text-base">【$1】</span>').replace(/\n/g, '<br>'); }
async function saveWork() { if (!AppState.currentContent) { showToast('warning', '无内容', ''); return; } const typeLabels = { couplet: '对联', acrostic: '藏头诗', seven: '七言诗', five: '五言诗', ci: '宋词' }; const work = { type: AppState.type, typeLabel: typeLabels[AppState.type], theme: AppState.theme, content: AppState.currentContent }; const result = await StorageService.saveWork(work); if (result.success) { showToast('success', '已收藏', ''); loadCollection(); } }
async function loadCollection() { AppState.works = await StorageService.getWorks(); renderCollection(); }
function renderCollection() { if (AppState.works.length === 0) { DOM.collectionList.innerHTML = '<p class="text-gray-400 text-sm text-center">暂无收藏</p>'; return; } DOM.collectionList.innerHTML = AppState.works.map(w => `<div class="p-3 bg-red-50 rounded-xl"><div class="font-medium text-red-700">📜 ${w.typeLabel}</div><div class="text-sm text-gray-600 mt-1 truncate">${w.theme || ''}</div><div class="text-xs text-gray-400 mt-1">${new Date(w.createdAt).toLocaleDateString()}</div></div>`).join(''); }
function closeCollection() { DOM.collectionPanel.classList.remove('open'); DOM.collectionOverlay.classList.add('hidden'); }
function loadSettings() { const c = AIService.getModelConfig() || {}; document.getElementById('api-url').value = c.apiUrl || ''; document.getElementById('api-key').value = c.apiKey || ''; document.getElementById('model-name').value = c.modelName || ''; }
function saveSettings() { const c = { apiUrl: document.getElementById('api-url').value.trim(), apiKey: document.getElementById('api-key').value.trim(), modelName: document.getElementById('model-name').value.trim() || 'GLM-4-Flash' }; if (!c.apiUrl || !c.apiKey) { showToast('warning', '请填写完整', ''); return; } AIService.saveModelConfig(c); DOM.settingsModal.classList.remove('show'); showToast('success', '配置已保存', ''); }
function showToast(type, title, message) { const icons = { success: '✅', error: '❌', warning: '⚠️', info: 'ℹ️' }; const colors = { success: 'bg-green-500', error: 'bg-red-500', warning: 'bg-yellow-500', info: 'bg-red-500' }; document.getElementById('toast-icon').className = `w-8 h-8 rounded-full flex items-center justify-center ${colors[type]}`; document.getElementById('toast-icon').textContent = icons[type]; document.getElementById('toast-title').textContent = title; document.getElementById('toast-message').textContent = message; DOM.toast.classList.remove('hidden'); setTimeout(() => DOM.toast.classList.add('hidden'), 3000); }
async function init() { initDOM(); initEvents(); await loadCollection(); const config = await AIService.initConfig(); if (!config) setTimeout(() => { DOM.settingsModal.classList.add('show'); showToast('info', '欢迎使用', '请配置 AI 模型'); }, 500); }
document.addEventListener('DOMContentLoaded', init);
